### ISSUE TITLE
ETF_FORMAT_MAX_COMPONENTS macro value

### ISSUE THREAD

**Issue by QuantumDeveloper** [amirduran/jpeg-encoder-decoder#2]
Hi,
I am currently porting your code to C# and faced with the issue that I dont see the real value of macro `ETF_FORMAT_MAX_COMPONENTS`

Can you please provide this information or say where I can find this info?

**Comment by amirduran** [comment]
This project was part of a bigger project called ETFShop (our university version of Photoshop). Obviously this value comes from the `format.h` file which is unfortunately not on this repo. `ETF_FORMAT_MAX_COMPONENTS` constant is integer defining max number of components in JPEG file. In a worst case you can play with some numbers, but I will try to find above mentioned file and add it to the repo.

**Comment by QuantumDeveloper** [comment]
OK, thanks. Hope you will find it

**Comment by amirduran** [comment]
This constant is defining number of components in a jpeg file. If the image is grayscale then it is 1, if it is normal colour image it is 3 `(Y Cb Cr)`.

Check this line 
https://github.com/amirduran/jpeg-encoder-decoder/blob/master/jpegdecode.cpp#L517

I assume `ETF_FORMAT_MAX_COMPONENTS` is integer between 1 and 4.

**Comment by QuantumDeveloper** [comment]
Thanks for your help. Will try to port your code to C# further :)

**Comment by QuantumDeveloper** [comment]
Want to ask one more question just not to open another issue.
In your code I found rawImagePointers variable. Its defined like: `uchar* rawImagePointers[ETF_FORMAT_MAX_COMPONENTS];`
So, I suppose this is array of arrays of bytes. like `vector<byte[ ]>()`. So, for each color component it has separate array of values like [0] = R component and have width * height bytes. Am I right?

**Comment by amirduran** [comment]
@QuantumDeveloper it is array of pointers pointing to unsigned char. In C# I would say it is vector of bytes like this `vector<byte>()`.

**Comment by QuantumDeveloper** [comment]
@amirduran  Ah, ok. So, this is just simple byte array of colors?

**Comment by QuantumDeveloper** [comment]
Just trying to understand why it is defined like `pointers[MAX_COMPONENTS]` and not as `unsigned char[]`
As we defined already, `MAX_COMPONENTS` max value is 4, so this is a bit strange for me

**Comment by amirduran** [comment]
@QuantumDeveloper I have just used pointers to work with data but you can use vector and it should not be the problem.
